const wordData = [
    { num: 1, english: "culture", meaning: "문화, 교양" },
    { num: 2, english: "experience", meaning: "경험" },
    { num: 3, english: "education", meaning: "교육" },
    { num: 4, english: "symbol", meaning: "상징" },
    { num: 5, english: "effect", meaning: "결과, 영향, 효과" },
    { num: 6, english: "liberty", meaning: "자유" },
    { num: 7, english: "affair", meaning: "사건, 일" },
    { num: 8, english: "comfort", meaning: "안락, 위안" },
    { num: 9, english: "tradition", meaning: "전통, 전설" },
    { num: 10, english: "subject", meaning: "학과, 주제, 백성" },
    { num: 11, english: "object", meaning: "물건, 목적" },
    { num: 12, english: "source", meaning: "출처, 근원" },
    { num: 13, english: "revolution", meaning: "혁명" },
    { num: 14, english: "pollution", meaning: "오염" },
    { num: 15, english: "system", meaning: "조직, 체계, 제도" },
    { num: 16, english: "triumph", meaning: "승리" },
    { num: 17, english: "respect", meaning: "존경" },
    { num: 18, english: "communication", meaning: "전달, 교통" },
    { num: 19, english: "foundation", meaning: "기초, 근거, 설립" },
    { num: 20, english: "glory", meaning: "영광" },
    { num: 21, english: "situation", meaning: "위치, 상황" },
    { num: 22, english: "competition", meaning: "경쟁" },
    { num: 23, english: "prairie", meaning: "대초원" },
    { num: 24, english: "effort", meaning: "노력" },
    { num: 25, english: "section", meaning: "부분, 구역" },
    { num: 26, english: "rein", meaning: "고삐" },
    { num: 27, english: "solution", meaning: "해결, 용해" },
    { num: 28, english: "honor", meaning: "명예, 경의" },
    { num: 29, english: "unity", meaning: "통일, 일치" },
    { num: 30, english: "population", meaning: "인구" },
    { num: 31, english: "direction", meaning: "방향, 지시" },
    { num: 32, english: "dialogue", meaning: "대화" },
    { num: 33, english: "republic", meaning: "공화국" },
    { num: 34, english: "method", meaning: "방법" },
    { num: 35, english: "increase", meaning: "증가" },
    { num: 36, english: "decrease", meaning: "감소" },
    { num: 37, english: "amount", meaning: "총액, 양" },
    { num: 38, english: "ancestor", meaning: "조상, 선조" },
    { num: 39, english: "voyage", meaning: "항해, 여행" },
    { num: 40, english: "sculpture", meaning: "조각" },
    { num: 41, english: "instrument", meaning: "기구, 악기" },
    { num: 42, english: "figure", meaning: "모습, 인물, 숫자" },
    { num: 43, english: "activity", meaning: "활동" },
    { num: 44, english: "cause", meaning: "원인, 이유" },
    { num: 45, english: "worth", meaning: "가치" },
    { num: 46, english: "accident", meaning: "사고" },
    { num: 47, english: "adventure", meaning: "모험" },
    { num: 48, english: "view", meaning: "경치, 의견" },
    { num: 49, english: "relative", meaning: "친척, 상대적인" },
    { num: 50, english: "superstition", meaning: "미신" },
    { num: 51, english: "habit", meaning: "습관, 버릇" },
    { num: 52, english: "wealth", meaning: "재산, 부" },
    { num: 53, english: "treasure", meaning: "보물" },
    { num: 54, english: "universe", meaning: "우주, 전 세계" },
    { num: 55, english: "adult", meaning: "어른" },
    { num: 56, english: "feast", meaning: "축제, 향연" },
    { num: 57, english: "resource", meaning: "자원, 수단" },
    { num: 58, english: "ruin", meaning: "파멸, 폐허" },
    { num: 59, english: "monument", meaning: "기념비, 기념물" },
    { num: 60, english: "information", meaning: "정보, 지식, 통지" },
    { num: 61, english: "appetite", meaning: "식욕" },
    { num: 62, english: "unification", meaning: "통일" },
    { num: 63, english: "mystery", meaning: "신비" },
    { num: 64, english: "thermometer", meaning: "온도계" },
    { num: 65, english: "burden", meaning: "짐" },
    { num: 66, english: "series", meaning: "연속, 시리즈" },
    { num: 67, english: "oath", meaning: "맹세, 선서" },
    { num: 68, english: "appointment", meaning: "임명, 약속" },
    { num: 69, english: "clue", meaning: "실마리, 단서" },
    { num: 70, english: "debt", meaning: "빚, 은혜" },
    { num: 71, english: "hydrogen", meaning: "수소" },
    { num: 72, english: "control", meaning: "통제, 지배" },
    { num: 73, english: "uniform", meaning: "제복" },
    { num: 74, english: "design", meaning: "계획, 설계" },
    { num: 75, english: "damage", meaning: "손해, 손상" },
    { num: 76, english: "custom", meaning: "관습, 습관" },
    { num: 77, english: "traffic", meaning: "교통" },
    { num: 78, english: "sophomore", meaning: "2학년생" },
    { num: 79, english: "temperature", meaning: "온도, 체온" },
    { num: 80, english: "limit", meaning: "제한, 한계" },
    { num: 81, english: "statue", meaning: "조각상" },
    { num: 82, english: "furniture", meaning: "가구" },
    { num: 83, english: "parade", meaning: "행렬" },
    { num: 84, english: "public", meaning: "공중, 공공의" },
    { num: 85, english: "pilgrim", meaning: "순례자, 청교도" },
    { num: 86, english: "greeting", meaning: "인사, 축하" },
    { num: 87, english: "language", meaning: "언어" },
    { num: 88, english: "opinion", meaning: "의견" },
    { num: 89, english: "athlete", meaning: "운동선수" },
    { num: 90, english: "supply", meaning: "공급" },
    { num: 91, english: "surface", meaning: "표면" },
    { num: 92, english: "electricity", meaning: "전기" },
    { num: 93, english: "order", meaning: "질서, 명령, 주문" },
    { num: 94, english: "spirit", meaning: "정신" },
    { num: 95, english: "purpose", meaning: "목적" },
    { num: 96, english: "promise", meaning: "약속, 가망" },
    { num: 97, english: "project", meaning: "계획" },
    { num: 98, english: "government", meaning: "정부, 정치" },
    { num: 99, english: "exercise", meaning: "운동, 연습" },
    { num: 100, english: "comparison", meaning: "비교" },
    { num: 101, english: "interest", meaning: "이익, 흥미" },
    { num: 102, english: "funeral", meaning: "장례식" },
    { num: 103, english: "senior", meaning: "선배, 연장자" },
    { num: 104, english: "junior", meaning: "후배, 연소자" },
    { num: 105, english: "democracy", meaning: "민주주의" },
    { num: 106, english: "general", meaning: "육군 대장, 육군 장군" },
    { num: 107, english: "admiral", meaning: "해군 대장, 해군 제독" },
    { num: 108, english: "edge", meaning: "날, 가장자리" },
    { num: 109, english: "biology", meaning: "생물학" },
    { num: 110, english: "danger", meaning: "위험" },
    { num: 111, english: "advice", meaning: "충고" },
    { num: 112, english: "practice", meaning: "연습, 실행" },
    { num: 113, english: "mammal", meaning: "포유동물" },
    { num: 114, english: "grade", meaning: "등급, 학년" },
    { num: 115, english: "score", meaning: "득점, 20" },
    { num: 116, english: "pause", meaning: "중지" },
    { num: 117, english: "pronunciation", meaning: "발음" },
    { num: 118, english: "stress", meaning: "압박, 강세" },
    { num: 119, english: "contest", meaning: "경쟁, 경기" },
    { num: 120, english: "horizon", meaning: "수평선, 지평선" },
    { num: 121, english: "principal", meaning: "교장, 주요한" },
    { num: 122, english: "might", meaning: "힘, may 과거" },
    { num: 123, english: "trouble", meaning: "근심, 고생" },
    { num: 124, english: "scar", meaning: "상처, 흔적" },
    { num: 125, english: "balance", meaning: "균형" },
    { num: 126, english: "proverb", meaning: "속담, 격언" },
    { num: 127, english: "semester", meaning: "학기" },
    { num: 128, english: "election", meaning: "선거" },
    { num: 129, english: "inning", meaning: "회" },
    { num: 130, english: "hollow", meaning: "구멍, 속이 빈" },
    { num: 131, english: "degree", meaning: "도, 정도" },
    { num: 132, english: "cemetery", meaning: "묘지" },
    { num: 133, english: "relay", meaning: "교대" },
    { num: 134, english: "spot", meaning: "장소, 현장" },
    { num: 135, english: "exchange", meaning: "교환" },
    { num: 136, english: "merchant", meaning: "상인" },
    { num: 137, english: "saying", meaning: "격언" },
    { num: 138, english: "refrigerator", meaning: "냉장고" },
    { num: 139, english: "crack", meaning: "갈라진 금" },
    { num: 140, english: "judge", meaning: "재판관" },
    { num: 141, english: "slave", meaning: "노예" },
    { num: 142, english: "settler", meaning: "이주민, 정착민" },
    { num: 143, english: "fare", meaning: "요금" },
    { num: 144, english: "gesture", meaning: "몸짓, 손짓" },
    { num: 145, english: "planet", meaning: "행성" },
    { num: 146, english: "type", meaning: "유형, 활자" },
    { num: 147, english: "secretary", meaning: "비서" },
    { num: 148, english: "devil", meaning: "악마" },
    { num: 149, english: "scholar", meaning: "학자" },
    { num: 150, english: "pardon", meaning: "용서" },
    { num: 151, english: "kindergarten", meaning: "유치원" },
    { num: 152, english: "detective", meaning: "탐정, 탐정의" },
    { num: 153, english: "license", meaning: "면허, 면허증" },
    { num: 154, english: "palace", meaning: "궁전" },
    { num: 155, english: "spade", meaning: "삽" },
    { num: 156, english: "square", meaning: "정사각형, 광장" },
    { num: 157, english: "fountain-pen", meaning: "만년필" },
    { num: 158, english: "harvest", meaning: "수확, 추수" },
    { num: 159, english: "tool", meaning: "도구" },
    { num: 160, english: "sword", meaning: "칼, 검" },
    { num: 161, english: "magazine", meaning: "잡지" },
    { num: 162, english: "stadium", meaning: "경기장" },
    { num: 163, english: "care", meaning: "걱정, 조심" },
    { num: 164, english: "beauty", meaning: "아름다움, 미인" },
    { num: 165, english: "museum", meaning: "박물관" },
    { num: 166, english: "sentence", meaning: "문장" },
    { num: 167, english: "memory", meaning: "기억" },
    { num: 168, english: "delight", meaning: "기쁨" },
    { num: 169, english: "passenger", meaning: "승객" },
    { num: 170, english: "skill", meaning: "솜씨, 숙련" },
    { num: 171, english: "journey", meaning: "여행" },
    { num: 172, english: "ceremony", meaning: "의식" },
    { num: 173, english: "hobby", meaning: "취미" },
    { num: 174, english: "president", meaning: "대통령, 회장" },
    { num: 175, english: "address", meaning: "주소, 연설" },
    { num: 176, english: "continent", meaning: "대륙" },
    { num: 177, english: "mankind", meaning: "인류, 인간" },
    { num: 178, english: "patient", meaning: "환자, 참을성 있는" },
    { num: 179, english: "site", meaning: "위치, 장소" },
    { num: 180, english: "marble", meaning: "대리석" },
    { num: 181, english: "stem", meaning: "줄기" },
    { num: 182, english: "slip", meaning: "미끄러짐, 실수" },
    { num: 183, english: "torch", meaning: "횃불" },
    { num: 184, english: "composer", meaning: "작곡가" },
    { num: 185, english: "invader", meaning: "침입자" },
    { num: 186, english: "trick", meaning: "계략, 장난" },
    { num: 187, english: "flight", meaning: "비행" },
    { num: 188, english: "castle", meaning: "성" },
    { num: 189, english: "envelope", meaning: "봉투" },
    { num: 190, english: "pal", meaning: "친구" },
    { num: 191, english: "vacation", meaning: "휴가, 방학" },
    { num: 192, english: "desert", meaning: "사막" },
    { num: 193, english: "event", meaning: "사건" },
    { num: 194, english: "theater", meaning: "극장" },
    { num: 195, english: "stage", meaning: "단계, 무대" },
    { num: 196, english: "error", meaning: "잘못, 과오" },
    { num: 197, english: "area", meaning: "지역, 면적" },
    { num: 198, english: "base", meaning: "기초, 토대" },
    { num: 199, english: "basement", meaning: "지하실" },
    { num: 200, english: "evil", meaning: "악, 나쁜" },
    { num: 201, english: "atom", meaning: "원자" },
    { num: 202, english: "poet", meaning: "시인" },
    { num: 203, english: "petal", meaning: "꽃잎" },
    { num: 204, english: "chance", meaning: "기회, 가능성" },
    { num: 205, english: "mind", meaning: "마음, 생각" },
    { num: 206, english: "climate", meaning: "기후, 풍토" },
    { num: 207, english: "suburb", meaning: "교외" },
    { num: 208, english: "throat", meaning: "목구멍" },
    { num: 209, english: "voice", meaning: "목소리" },
    { num: 210, english: "valley", meaning: "골짜기, 계곡" },
    { num: 211, english: "Puritan", meaning: "청교도" },
    { num: 212, english: "feather", meaning: "깃털" },
    { num: 213, english: "amateur", meaning: "비전문가" },
    { num: 214, english: "nation", meaning: "국가, 국민" },
    { num: 215, english: "puzzle", meaning: "수수께끼" },
    { num: 216, english: "riddle", meaning: "수수께끼" },
    { num: 217, english: "rear", meaning: "뒤쪽" },
    { num: 218, english: "battle", meaning: "전투" },
    { num: 219, english: "laundry", meaning: "세탁소" },
    { num: 220, english: "shower", meaning: "소나기, 샤워" },
    { num: 221, english: "navy", meaning: "해군" },
    { num: 222, english: "Mars", meaning: "화성" },
    { num: 223, english: "gallery", meaning: "화랑, 미술관" },
    { num: 224, english: "guest", meaning: "손님" },
    { num: 225, english: "folk", meaning: "사람들, 가족" },
    { num: 226, english: "problem", meaning: "문제" },
    { num: 227, english: "jewel", meaning: "보석" },
    { num: 228, english: "garage", meaning: "차고" },
    { num: 229, english: "fault", meaning: "결점, 잘못" },
    { num: 230, english: "lantern", meaning: "랜턴, 초롱불" },
    { num: 231, english: "import", meaning: "수입" },
    { num: 232, english: "angle", meaning: "각도, 관점" },
    { num: 233, english: "match", meaning: "시합" },
    { num: 234, english: "stripe", meaning: "줄무늬" },
    { num: 235, english: "pulse", meaning: "맥박" },
    { num: 236, english: "powder", meaning: "가루, 화약" },
    { num: 237, english: "flood", meaning: "홍수, 넘치다" },
    { num: 238, english: "bush", meaning: "수풀, 덤불" },
    { num: 239, english: "branch", meaning: "가지, 지점" },
    { num: 240, english: "hero", meaning: "영웅, 주인공" },
    { num: 241, english: "heaven", meaning: "하늘, 천국" },
    { num: 242, english: "exit", meaning: "출구" },
    { num: 243, english: "beast", meaning: "짐승" },
    { num: 244, english: "century", meaning: "세기, 100년" },
    { num: 245, english: "coeducation", meaning: "남녀 공학" },
    { num: 246, english: "twin", meaning: "쌍둥이의 한 사람" },
    { num: 247, english: "wound", meaning: "상처, 부상" },
    { num: 248, english: "metal", meaning: "금속" },
    { num: 249, english: "insect", meaning: "곤충" },
    { num: 250, english: "track", meaning: "지나간 자국" },
    { num: 251, english: "deserve", meaning: "할 만하다" },
    { num: 252, english: "survive", meaning: "살아남다" },
    { num: 253, english: "create", meaning: "창조하다" },
    { num: 254, english: "describe", meaning: "묘사하다" },
    { num: 255, english: "select", meaning: "고르다" },
    { num: 256, english: "hesitate", meaning: "망설이다" },
    { num: 257, english: "declare", meaning: "선언, 발표" },
    { num: 258, english: "pretend", meaning: "인 체하다" },
    { num: 259, english: "struggle", meaning: "싸우다, 노력" },
    { num: 260, english: "explore", meaning: "탐험하다" },
    { num: 261, english: "astonish", meaning: "놀라게 하다" },
    { num: 262, english: "disappoint", meaning: "실망시키다" },
    { num: 263, english: "attract", meaning: "끌다" },
    { num: 264, english: "celebrate", meaning: "축하하다" },
    { num: 265, english: "explode", meaning: "폭발하다" },
    { num: 266, english: "include", meaning: "포함하다" },
    { num: 267, english: "protect", meaning: "보호하다" },
    { num: 268, english: "introduce", meaning: "소개, 도입" },
    { num: 269, english: "produce", meaning: "생산하다" },
    { num: 270, english: "chase", meaning: "쫓다, 추적" },
    { num: 271, english: "scratch", meaning: "할퀴다, 긁다" },
    { num: 272, english: "crash", meaning: "충돌하다" },
    { num: 273, english: "stare", meaning: "응시하다" },
    { num: 274, english: "gaze", meaning: "응시하다" },
    { num: 275, english: "scare", meaning: "놀라게 하다" },
    { num: 276, english: "grab", meaning: "움켜잡다" },
    { num: 277, english: "guard", meaning: "지키다" },
    { num: 278, english: "discuss", meaning: "토론하다" },
    { num: 279, english: "shrug", meaning: "어깨를 으쓱하다" },
    { num: 280, english: "sniff", meaning: "냄새 맡다" },
    { num: 281, english: "scream", meaning: "비명을 지르다" },
    { num: 282, english: "rid", meaning: "제거하다" },
    { num: 283, english: "surround", meaning: "둘러싸다" },
    { num: 284, english: "cleave", meaning: "쪼개다, 찢다" },
    { num: 285, english: "carve", meaning: "새기다, 조각" },
    { num: 286, english: "except", meaning: "제외하다" },
    { num: 287, english: "invent", meaning: "발명하다" },
    { num: 288, english: "search", meaning: "찾다, 수색" },
    { num: 289, english: "abuse", meaning: "남용, 학대" },
    { num: 290, english: "owe", meaning: "힘입다, 빚지다" },
    { num: 291, english: "bless", meaning: "축복하다" },
    { num: 292, english: "graduate", meaning: "졸업하다" },
    { num: 293, english: "replace", meaning: "대신하다" },
    { num: 294, english: "collect", meaning: "모으다" },
    { num: 295, english: "upset", meaning: "뒤엎다, 당황케" },
    { num: 296, english: "arrest", meaning: "체포하다" },
    { num: 297, english: "prove", meaning: "증명하다" },
    { num: 298, english: "yell", meaning: "외치다" },
    { num: 299, english: "howl", meaning: "짖다, 울부짖다" },
    { num: 300, english: "halt", meaning: "멈추다" },
    { num: 301, english: "leak", meaning: "새다" },
    { num: 302, english: "behave", meaning: "행동하다" },
    { num: 303, english: "wrap", meaning: "싸다, 포장하다" },
    { num: 304, english: "locate", meaning: "위치하다" },
    { num: 305, english: "charge", meaning: "청구하다" },
    { num: 306, english: "review", meaning: "복습하다" },
    { num: 307, english: "refuse", meaning: "거절하다" },
    { num: 308, english: "complain", meaning: "불평하다" },
    { num: 309, english: "remain", meaning: "남다, 유적" },
    { num: 310, english: "warn", meaning: "경고하다" },
    { num: 311, english: "bend", meaning: "구부리다" },
    { num: 312, english: "suffer", meaning: "겪다, 괴로워하다" },
    { num: 313, english: "whisper", meaning: "속삭이다" },
    { num: 314, english: "prepare", meaning: "준비하다" },
    { num: 315, english: "roar", meaning: "으르렁거리다" },
    { num: 316, english: "float", meaning: "뜨다, 띄우다" },
    { num: 317, english: "drag", meaning: "질질 끌다" },
    { num: 318, english: "overhear", meaning: "엿듣다" },
    { num: 319, english: "slide", meaning: "미끄러지다" },
    { num: 320, english: "suck", meaning: "빨다" },
    { num: 321, english: "bother", meaning: "괴롭히다" },
    { num: 322, english: "deal", meaning: "분배, 거래" },
    { num: 323, english: "treat", meaning: "다루다, 대우" },
    { num: 324, english: "destroy", meaning: "파괴하다" },
    { num: 325, english: "accept", meaning: "받아들이다" },
    { num: 326, english: "depend", meaning: "의지하다" },
    { num: 327, english: "nod", meaning: "끄덕이다" },
    { num: 328, english: "remove", meaning: "옮기다, 치우다" },
    { num: 329, english: "beat", meaning: "때리다, 이기다" },
    { num: 330, english: "clap", meaning: "손뼉을 치다, 치다" },
    { num: 331, english: "feed", meaning: "기르다" },
    { num: 332, english: "obtain", meaning: "얻다, 획득하다" },
    { num: 333, english: "drown", meaning: "물에 빠지다" },
    { num: 334, english: "remind", meaning: "생각나게 하다" },
    { num: 335, english: "occur", meaning: "일어나다, 생각나다" },
    { num: 336, english: "ache", meaning: "아프다" },
    { num: 337, english: "repeat", meaning: "되풀이하다" },
    { num: 338, english: "attend", meaning: "참석하다" },
    { num: 339, english: "sigh", meaning: "한숨 쉬다" },
    { num: 340, english: "pray", meaning: "빌다, 기도하다" },
    { num: 341, english: "press", meaning: "누르다" },
    { num: 342, english: "bear", meaning: "낳다, 참다, 곰" },
    { num: 343, english: "follow", meaning: "따르다" },
    { num: 344, english: "hate", meaning: "미워하다" },
    { num: 345, english: "frighten", meaning: "놀라게 하다" },
    { num: 346, english: "shout", meaning: "외치다" },
    { num: 347, english: "mention", meaning: "말하다" },
    { num: 348, english: "waste", meaning: "낭비하다" },
    { num: 349, english: "borrow", meaning: "빌리다" },
    { num: 350, english: "complete", meaning: "완성하다" },
    { num: 351, english: "excellent", meaning: "뛰어난, 우수한" },
    { num: 352, english: "competent", meaning: "유능한, 충분한" },
    { num: 353, english: "religious", meaning: "종교적인" },
    { num: 354, english: "favorite", meaning: "아주 좋아하는" },
    { num: 355, english: "entire", meaning: "전체의" },
    { num: 356, english: "primary", meaning: "주요한, 초보의" },
    { num: 357, english: "similar", meaning: "비슷한" },
    { num: 358, english: "precious", meaning: "귀중한" },
    { num: 359, english: "normal", meaning: "정상의, 보통의" },
    { num: 360, english: "popular", meaning: "인기 있는" },
    { num: 361, english: "compulsory", meaning: "의무, 필수" },
    { num: 362, english: "curious", meaning: "호기심이 강한" },
    { num: 363, english: "independent", meaning: "독립의" },
    { num: 364, english: "intimate", meaning: "친밀한" },
    { num: 365, english: "delicious", meaning: "맛있는" },
    { num: 366, english: "valuable", meaning: "귀중한" },
    { num: 367, english: "grave", meaning: "중대한, 무덤" },
    { num: 368, english: "elementary", meaning: "초보의" },
    { num: 369, english: "crazy", meaning: "미친" },
    { num: 370, english: "contrary", meaning: "반대의" },
    { num: 371, english: "regular", meaning: "규칙적인" },
    { num: 372, english: "social", meaning: "사회의" },
    { num: 373, english: "straight", meaning: "똑바른" },
    { num: 374, english: "noble", meaning: "고귀한, 고상한" },
    { num: 375, english: "anxious", meaning: "걱정되는, 열망하는" },
    { num: 376, english: "international", meaning: "국제적인" },
    { num: 377, english: "greedy", meaning: "탐욕스러운" },
    { num: 378, english: "stupid", meaning: "어리석은" },
    { num: 379, english: "silly", meaning: "어리석은" },
    { num: 380, english: "lonely", meaning: "고독한" },
    { num: 381, english: "dirty", meaning: "더러운" },
    { num: 382, english: "various", meaning: "여러 가지의" },
    { num: 383, english: "private", meaning: "개인의, 사적인" },
    { num: 384, english: "vain", meaning: "헛된, 무익한" },
    { num: 385, english: "sore", meaning: "아픈, 상처" },
    { num: 386, english: "fierce", meaning: "사나운, 맹렬한" },
    { num: 387, english: "firm", meaning: "굳은, 견고한" },
    { num: 388, english: "solar", meaning: "태양의" },
    { num: 389, english: "smart", meaning: "멋진, 영리한" },
    { num: 390, english: "single", meaning: "단 하나의" },
    { num: 391, english: "diligent", meaning: "부지런한" },
    { num: 392, english: "serious", meaning: "진지한, 심각한" },
    { num: 393, english: "fresh", meaning: "새로운, 신선한" },
    { num: 394, english: "empty", meaning: "빈" },
    { num: 395, english: "mild", meaning: "온화한, 상냥한" },
    { num: 396, english: "amazing", meaning: "놀라운" },
    { num: 397, english: "charming", meaning: "매력적인" },
    { num: 398, english: "boring", meaning: "지루한, 따분한" },
    { num: 399, english: "giant", meaning: "거인" },
    { num: 400, english: "huge", meaning: "거대한" },
    { num: 401, english: "tiny", meaning: "아주 작은" },
    { num: 402, english: "fair", meaning: "공평한, 아름다운" },
    { num: 403, english: "tough", meaning: "단단한, 질긴" },
    { num: 404, english: "foreign", meaning: "외국의" },
    { num: 405, english: "modern", meaning: "현대의" },
    { num: 406, english: "expensive", meaning: "값비싼" },
    { num: 407, english: "harmful", meaning: "해로운" },
    { num: 408, english: "calm", meaning: "평온한" },
    { num: 409, english: "special", meaning: "특별한" },
    { num: 410, english: "steady", meaning: "확고한, 착실한" },
    { num: 411, english: "hay", meaning: "건초" },
    { num: 412, english: "revival", meaning: "부활" },
    { num: 413, english: "million", meaning: "백만, 다수" },
    { num: 414, english: "crop", meaning: "농작물, 수확" },
    { num: 415, english: "shade", meaning: "그늘" },
    { num: 416, english: "company", meaning: "친구, 교제, 회사" },
    { num: 417, english: "canal", meaning: "운하" },
    { num: 418, english: "wagon", meaning: "짐마차" },
    { num: 419, english: "fact", meaning: "사실" },
    { num: 420, english: "joy", meaning: "기쁨" },
    { num: 421, english: "concert", meaning: "음악회, 연주회" },
    { num: 422, english: "rule", meaning: "규칙, 지배하다" },
    { num: 423, english: "suitcase", meaning: "여행 가방" },
    { num: 424, english: "weight", meaning: "무게" },
    { num: 425, english: "hurray", meaning: "만세" },
    { num: 426, english: "mail", meaning: "우편" },
    { num: 427, english: "log", meaning: "통나무" },
    { num: 428, english: "hut", meaning: "오두막집" },
    { num: 429, english: "tax", meaning: "세금" },
    { num: 430, english: "dye", meaning: "물들이다, 물감" },
    { num: 431, english: "earnings", meaning: "돈벌이" },
    { num: 432, english: "flame", meaning: "불꽃" },
    { num: 433, english: "shape", meaning: "모양" },
    { num: 434, english: "chest", meaning: "가슴, 상자" },
    { num: 435, english: "chain", meaning: "사슬" },
    { num: 436, english: "cost", meaning: "비용, 비용이 들다" },
    { num: 437, english: "coast", meaning: "해안" },
    { num: 438, english: "circle", meaning: "원, 집단" },
    { num: 439, english: "heart", meaning: "심장, 마음" },
    { num: 440, english: "nature", meaning: "자연, 성질" },
    { num: 441, english: "fever", meaning: "열, 열병" },
    { num: 442, english: "tongue", meaning: "혀, 언어" },
    { num: 443, english: "trust", meaning: "신용, 신뢰" },
    { num: 444, english: "whisker", meaning: "구레나룻" },
    { num: 445, english: "prison", meaning: "감옥" },
    { num: 446, english: "blood", meaning: "피, 혈액" },
    { num: 447, english: "loaf", meaning: "빵 한 덩어리" },
    { num: 448, english: "list", meaning: "목록" },
    { num: 449, english: "fence", meaning: "울타리" },
    { num: 450, english: "enemy", meaning: "적" },
    { num: 451, english: "thief", meaning: "도둑" },
    { num: 452, english: "data", meaning: "자료" },
    { num: 453, english: "soldier", meaning: "군인" },
    { num: 454, english: "musician", meaning: "음악가" },
    { num: 455, english: "capital", meaning: "수도, 자본" },
    { num: 456, english: "course", meaning: "진로, 과정" },
    { num: 457, english: "diary", meaning: "일기" },
    { num: 458, english: "squirrel", meaning: "다람쥐" },
    { num: 459, english: "dawn", meaning: "새벽" },
    { num: 460, english: "shadow", meaning: "그림자" },
    { num: 461, english: "ditch", meaning: "도랑" },
    { num: 462, english: "crew", meaning: "승무원" },
    { num: 463, english: "stomach", meaning: "위" },
    { num: 464, english: "neighbor", meaning: "이웃 사람" },
    { num: 465, english: "servant", meaning: "하인" },
    { num: 466, english: "hunger", meaning: "굶주림" },
    { num: 467, english: "tomb", meaning: "무덤, 묘" },
    { num: 468, english: "taste", meaning: "맛, 취미" },
    { num: 469, english: "sign", meaning: "신호, 기호" },
    { num: 470, english: "stair", meaning: "계단" },
    { num: 471, english: "trip", meaning: "여행" },
    { num: 472, english: "brain", meaning: "뇌, 두뇌" },
    { num: 473, english: "trumpet", meaning: "나팔, 트럼펫" },
    { num: 474, english: "speech", meaning: "말, 연설" },
    { num: 475, english: "thumb", meaning: "엄지손가락" },
    { num: 476, english: "horn", meaning: "뿔, 경적" },
    { num: 477, english: "chief", meaning: "장, 주요한" },
    { num: 478, english: "trousers", meaning: "바지" },
    { num: 479, english: "prince", meaning: "왕자" },
    { num: 480, english: "force", meaning: "힘, 강요하다" },
    { num: 481, english: "sight", meaning: "광경" },
    { num: 482, english: "space", meaning: "공간, 우주" },
    { num: 483, english: "wool", meaning: "양모" },
    { num: 484, english: "expressway", meaning: "고속도로" },
    { num: 485, english: "science", meaning: "과학" },
    { num: 486, english: "examination", meaning: "시험, 조사" },
    { num: 487, english: "jar", meaning: "항아리" },
    { num: 488, english: "salt", meaning: "소금" },
    { num: 489, english: "death", meaning: "죽음, 사망" },
    { num: 490, english: "saw", meaning: "톱" },
    { num: 491, english: "swing", meaning: "그네, 진동" },
    { num: 492, english: "wish", meaning: "소원, 원하다" },
    { num: 493, english: "grain", meaning: "곡식, 낟알" },
    { num: 494, english: "eraser", meaning: "지우개" },
    { num: 495, english: "alphabet", meaning: "알파벳, 문자" },
    { num: 496, english: "shoulder", meaning: "어깨" },
    { num: 497, english: "nephew", meaning: "조카" },
    { num: 498, english: "niece", meaning: "조카딸" },
    { num: 499, english: "library", meaning: "도서관" },
    { num: 500, english: "factory", meaning: "공장" },
    { num: 501, english: "giraffe", meaning: "기린" },
    { num: 502, english: "hawk", meaning: "매" },
    { num: 503, english: "pigeon", meaning: "비둘기" },
    { num: 504, english: "bowl", meaning: "사발, 그릇" },
    { num: 505, english: "scene", meaning: "장면, 현장" },
    { num: 506, english: "life", meaning: "생명, 생활, 일생" },
    { num: 507, english: "earth", meaning: "지구, 땅, 흙" },
    { num: 508, english: "pill", meaning: "알약" },
    { num: 509, english: "math", meaning: "수학" },
    { num: 510, english: "ocean", meaning: "대양" },
    { num: 511, english: "price", meaning: "가격" },
    { num: 512, english: "row", meaning: "줄, 열" },
    { num: 513, english: "schedule", meaning: "예정표" },
    { num: 514, english: "machine", meaning: "기계" },
    { num: 515, english: "route", meaning: "길" },
    { num: 516, english: "ivy", meaning: "담쟁이덩굴" },
    { num: 517, english: "gift", meaning: "선물, 재능" },
    { num: 518, english: "candle", meaning: "양초" },
    { num: 519, english: "joke", meaning: "농담" },
    { num: 520, english: "art", meaning: "예술, 미술, 기술" },
    { num: 521, english: "corn", meaning: "곡물" },
    { num: 522, english: "pet", meaning: "애완동물" },
    { num: 523, english: "robber", meaning: "강도" },
    { num: 524, english: "cheek", meaning: "뺨, 볼" },
    { num: 525, english: "clerk", meaning: "사무원, 점원" },
    { num: 526, english: "cookie", meaning: "쿠키" },
    { num: 527, english: "army", meaning: "육군, 군대" },
    { num: 528, english: "nurse", meaning: "간호사" },
    { num: 529, english: "master", meaning: "주인, 정복하다" },
    { num: 530, english: "lock", meaning: "자물쇠" },
    { num: 531, english: "moment", meaning: "순간" },
    { num: 532, english: "sheet", meaning: "침대시트, 한 장" },
    { num: 533, english: "monk", meaning: "승려" },
    { num: 534, english: "teenager", meaning: "십대 소년소녀" },
    { num: 535, english: "closet", meaning: "벽장" },
    { num: 536, english: "handle", meaning: "손잡이" },
    { num: 537, english: "guide", meaning: "안내자" },
    { num: 538, english: "bar", meaning: "막대기, 빗장" },
    { num: 539, english: "ostrich", meaning: "타조" },
    { num: 540, english: "knee", meaning: "무릎" },
    { num: 541, english: "cricket", meaning: "크리켓" },
    { num: 542, english: "deck", meaning: "갑판" },
    { num: 543, english: "bit", meaning: "조금" },
    { num: 544, english: "silk", meaning: "비단" },
    { num: 545, english: "jean", meaning: "진바지" },
    { num: 546, english: "cotton", meaning: "솜, 목화" },
    { num: 547, english: "drum", meaning: "북" },
    { num: 548, english: "sand", meaning: "모래" },
    { num: 549, english: "shock", meaning: "충격" },
    { num: 550, english: "march", meaning: "행진" },
    { num: 551, english: "cage", meaning: "새장, 우리" },
    { num: 552, english: "whole", meaning: "전부" },
    { num: 553, english: "change", meaning: "변화, 교환, 잔돈" },
    { num: 554, english: "department", meaning: "부, 국" },
    { num: 555, english: "office", meaning: "사무실" },
    { num: 556, english: "ticket", meaning: "표, 입장권" },
    { num: 557, english: "energy", meaning: "힘, 정력, 활기" },
    { num: 558, english: "idea", meaning: "생각, 이념" },
    { num: 559, english: "hospital", meaning: "병원" },
    { num: 560, english: "noise", meaning: "소음, 소리" },
    { num: 561, english: "sample", meaning: "견본" },
    { num: 562, english: "example", meaning: "예, 보기" },
    { num: 563, english: "lesson", meaning: "학과, 교훈" },
    { num: 564, english: "plenty", meaning: "풍부" },
    { num: 565, english: "luck", meaning: "행운" },
    { num: 566, english: "comedy", meaning: "희극, 코미디" },
    { num: 567, english: "health", meaning: "건강" },
    { num: 568, english: "history", meaning: "역사" },
    { num: 569, english: "forest", meaning: "숲" },
    { num: 570, english: "stream", meaning: "흐름, 개울" },
    { num: 571, english: "future", meaning: "미래" },
    { num: 572, english: "state", meaning: "상태, 주, 국가" },
    { num: 573, english: "temple", meaning: "절, 사원" },
    { num: 574, english: "dictionary", meaning: "사전" },
    { num: 575, english: "grammar", meaning: "문법" },
    { num: 576, english: "college", meaning: "단과 대학" },
    { num: 577, english: "husband", meaning: "남편" },
    { num: 578, english: "daughter", meaning: "딸" },
    { num: 579, english: "captain", meaning: "선장, 주장" },
    { num: 580, english: "booth", meaning: "오두막, 작은 집" },
    { num: 582, english: "iceberg", meaning: "빙산" },
    { num: 583, english: "bubble", meaning: "거품" },
    { num: 584, english: "bottom", meaning: "밑바닥" },
    { num: 585, english: "prize", meaning: "상, 상품" },
    { num: 586, english: "bean", meaning: "콩" },
    { num: 587, english: "race", meaning: "경주, 인종, 민족" },
    { num: 588, english: "engineer", meaning: "기사, 기술자" },
    { num: 589, english: "photographer", meaning: "사진사" },
    { num: 590, english: "reason", meaning: "이유, 이성" },
    { num: 591, english: "subway", meaning: "지하도, 지하철" },
    { num: 592, english: "fog", meaning: "안개" },
    { num: 593, english: "answer", meaning: "대답" },
    { num: 594, english: "dining room", meaning: "식당" },
    { num: 595, english: "step", meaning: "걸음" },
    { num: 596, english: "heat", meaning: "열, 더위" },
    { num: 597, english: "bone", meaning: "뼈" },
    { num: 598, english: "plant", meaning: "식물" },
    { num: 599, english: "lamb", meaning: "새끼 양" },
    { num: 600, english: "rate", meaning: "비율, 속도, 요금" },
    { num: 601, english: "turtle", meaning: "거북" },
    { num: 602, english: "bay", meaning: "만" },
    { num: 603, english: "holiday", meaning: "휴일, 휴가" },
    { num: 604, english: "center", meaning: "중심" },
    { num: 605, english: "cash", meaning: "현금" },
    { num: 606, english: "wolf", meaning: "늑대" },
    { num: 607, english: "operator", meaning: "기사, 교환수" },
    { num: 608, english: "fur", meaning: "털, 모피" },
    { num: 609, english: "shore", meaning: "물가, 해안" },
    { num: 610, english: "owl", meaning: "올빼미" },
    { num: 611, english: "hunter", meaning: "사냥꾼" },
    { num: 612, english: "pumpkin", meaning: "호박" },
    { num: 613, english: "handshake", meaning: "악수" },
    { num: 614, english: "bike", meaning: "자전거" },
    { num: 615, english: "beach", meaning: "해안" },
    { num: 616, english: "God", meaning: "신" },
    { num: 617, english: "cough", meaning: "기침" },
    { num: 618, english: "shell", meaning: "조개, 껍질" },
    { num: 619, english: "business", meaning: "사업, 일, 사무" },
    { num: 620, english: "restaurant", meaning: "식당" },
    { num: 621, english: "sheep", meaning: "양" },
    { num: 622, english: "officer", meaning: "공무원, 장교" },
    { num: 623, english: "hometown", meaning: "고향" },
    { num: 624, english: "coil", meaning: "감긴 것, 코일" },
    { num: 625, english: "ceiling", meaning: "천장" },
    { num: 626, english: "turkey", meaning: "칠면조" },
    { num: 627, english: "towel", meaning: "수건" },
    { num: 628, english: "matter", meaning: "물질, 일, 문제" },
    { num: 629, english: "chopstick", meaning: "젓가락" },
    { num: 630, english: "seat", meaning: "좌석, 앉히다" },
    { num: 631, english: "board", meaning: "판자, 뱃전" },
    { num: 632, english: "goal", meaning: "목표, 골" },
    { num: 633, english: "drugstore", meaning: "약국" },
    { num: 634, english: "rat", meaning: "쥐" },
    { num: 635, english: "butterfly", meaning: "나비" },
    { num: 636, english: "flute", meaning: "플루트" },
    { num: 637, english: "couple", meaning: "한 쌍, 부부" },
    { num: 638, english: "beer", meaning: "맥주" },
    { num: 639, english: "background", meaning: "배경" },
    { num: 640, english: "bottle", meaning: "병" },
    { num: 641, english: "body", meaning: "몸, 신체" },
    { num: 642, english: "group", meaning: "집단, 무리" },
    { num: 643, english: "village", meaning: "마을" },
    { num: 644, english: "beef", meaning: "쇠고기" },
    { num: 645, english: "load", meaning: "짐, 부담" },
    { num: 646, english: "coin", meaning: "동전, 화폐" },
    { num: 647, english: "bookstore", meaning: "서점" },
    { num: 648, english: "label", meaning: "꼬리표, 상표" },
    { num: 649, english: "port", meaning: "항구" },
    { num: 650, english: "quarter", meaning: "4분의 1, 15분" },
    { num: 651, english: "sunrise", meaning: "해돋이, 일출" },
    { num: 652, english: "sunshine", meaning: "햇빛" },
    { num: 653, english: "wedding", meaning: "결혼식" },
    { num: 654, english: "crown", meaning: "왕관" },
    { num: 655, english: "seed", meaning: "씨" },
    { num: 656, english: "coal", meaning: "석탄" },
    { num: 657, english: "comb", meaning: "빗" },
    { num: 658, english: "dream", meaning: "꿈" },
    { num: 659, english: "sugar", meaning: "설탕" },
    { num: 660, english: "mile", meaning: "마일" },
    { num: 661, english: "flashlight", meaning: "플래시" },
    { num: 662, english: "vegetable", meaning: "채소, 야채" },
    { num: 663, english: "mouse", meaning: "생쥐" },
    { num: 664, english: "wood", meaning: "나무, 숲" },
    { num: 665, english: "war", meaning: "전쟁" },
    { num: 666, english: "ground", meaning: "땅, 운동장" },
    { num: 667, english: "belt", meaning: "허리띠, 띠" },
    { num: 668, english: "tourist", meaning: "관광객, 여행자" },
    { num: 669, english: "airport", meaning: "공항" },
    { num: 670, english: "passport", meaning: "여권" },
    { num: 671, english: "plate", meaning: "접시" },
    { num: 672, english: "stone", meaning: "돌" },
    { num: 673, english: "downtown", meaning: "상가, 번화가" },
    { num: 674, english: "cousin", meaning: "사촌" },
    { num: 675, english: "tooth", meaning: "이, 치아" },
    { num: 676, english: "potato", meaning: "감자" },
    { num: 677, english: "blanket", meaning: "담요" },
    { num: 678, english: "creek", meaning: "시냇물" },
    { num: 679, english: "nail", meaning: "손톱" },
    { num: 680, english: "letter", meaning: "편지, 문자" },
    { num: 681, english: "date", meaning: "날짜" },
    { num: 682, english: "store", meaning: "가게, 저장" },
    { num: 683, english: "beggar", meaning: "거지" },
    { num: 684, english: "bedside", meaning: "침대 곁" },
    { num: 685, english: "deer", meaning: "사슴" },
    { num: 686, english: "bill", meaning: "계산서, 지폐" },
    { num: 687, english: "doll", meaning: "인형" },
    { num: 688, english: "pepper", meaning: "후추" },
    { num: 689, english: "frog", meaning: "개구리" },
    { num: 690, english: "rest", meaning: "휴식, 나머지" },
    { num: 691, english: "tower", meaning: "탑" },
    { num: 692, english: "bridge", meaning: "다리" },
    { num: 693, english: "cloth", meaning: "천, 직물" },
    { num: 694, english: "post", meaning: "우편, 우편물" },
    { num: 695, english: "snake", meaning: "뱀" },
    { num: 696, english: "job", meaning: "직업, 일" },
    { num: 697, english: "town", meaning: "읍, 도시" },
    { num: 698, english: "fun", meaning: "재미" },
    { num: 699, english: "bathroom", meaning: "욕실" },
    { num: 700, english: "tail", meaning: "꼬리" },
    { num: 701, english: "mayor", meaning: "시장" },
    { num: 702, english: "piece", meaning: "조각" },
    { num: 703, english: "fruit", meaning: "과일" },
    { num: 704, english: "British", meaning: "영국인, 영국의" },
    { num: 705, english: "French", meaning: "프랑스인, 프랑스의" },
    { num: 706, english: "German", meaning: "독일인, 독일의" },
    { num: 707, english: "sale", meaning: "판매" },
    { num: 708, english: "rope", meaning: "밧줄" },
    { num: 709, english: "umbrella", meaning: "우산" },
    { num: 710, english: "dollar", meaning: "달러" },
    { num: 711, english: "mistake", meaning: "잘못, 착각" },
    { num: 712, english: "birth", meaning: "출생" },
    { num: 713, english: "pilot", meaning: "안내인, 조종사" },
    { num: 714, english: "none", meaning: "아무도 않다" },
    { num: 715, english: "front", meaning: "앞, 정면" },
    { num: 716, english: "present", meaning: "현재, 선물, 출석한" },
    { num: 717, english: "nickname", meaning: "별명, 애칭" },
    { num: 718, english: "telephone", meaning: "전화" },
    { num: 719, english: "pair", meaning: "한 쌍" },
    { num: 720, english: "weather", meaning: "날씨" },
    { num: 721, english: "dish", meaning: "접시, 요리" },
    { num: 722, english: "hole", meaning: "구멍" },
    { num: 723, english: "plane", meaning: "비행기" },
    { num: 724, english: "living room", meaning: "거실" },
    { num: 725, english: "gun", meaning: "총" },
    { num: 726, english: "meat", meaning: "고기" },
    { num: 727, english: "cover", meaning: "덮개, 포지" },
    { num: 728, english: "grass", meaning: "풀, 잔디" },
    { num: 729, english: "watch", meaning: "손목시계, 주의" },
    { num: 730, english: "word", meaning: "낱말" },
    { num: 731, english: "explain", meaning: "설명하다" },
    { num: 732, english: "wear", meaning: "입다, 착용하다" },
    { num: 733, english: "amuse", meaning: "즐겁게 하다" },
    { num: 734, english: "suppose", meaning: "가정, 상상" },
    { num: 735, english: "leap", meaning: "뛰다" },
    { num: 736, english: "bury", meaning: "묻다" },
    { num: 737, english: "engage", meaning: "약속, 고용" },
    { num: 378, english: "sow", meaning: "씨를 뿌리다" },
    { num: 739, english: "lift", meaning: "들어올리다" },
    { num: 740, english: "bow", meaning: "절하다, 인사" },
    { num: 741, english: "rub", meaning: "비비다, 문지르다" },
    { num: 742, english: "bite", meaning: "물다" },
    { num: 743, english: "vote", meaning: "투표하다" },
    { num: 744, english: "hop", meaning: "뛰다" },
    { num: 745, english: "imagine", meaning: "상상, 생각" },
    { num: 746, english: "allow", meaning: "허락하다" },
    { num: 747, english: "offer", meaning: "제공하다" },
    { num: 748, english: "gain", meaning: "얻다, 이기다" },
    { num: 749, english: "alarm", meaning: "놀람, 경보" },
    { num: 750, english: "obey", meaning: "복종하다" },
    { num: 751, english: "steal", meaning: "훔치다" },
    { num: 752, english: "dig", meaning: "파다" },
    { num: 753, english: "choose", meaning: "고르다, 선택" },
    { num: 754, english: "receive", meaning: "받다" },
    { num: 755, english: "bet", meaning: "걸다, 돈을 걸다" },
    { num: 756, english: "hurt", meaning: "상처를 입히다" },
    { num: 757, english: "burn", meaning: "타다, 태우다" },
    { num: 758, english: "sink", meaning: "가라앉다" },
    { num: 759, english: "decide", meaning: "결정, 결심" },
    { num: 760, english: "beg", meaning: "구걸하다" },
    { num: 761, english: "reply", meaning: "대답하다" },
    { num: 762, english: "tear", meaning: "찢다, 눈물" },
    { num: 763, english: "flow", meaning: "흐르다, 넘쳐 흐르다" },
    { num: 764, english: "remember", meaning: "기억하다" },
    { num: 765, english: "appear", meaning: "나타나다, 같다" },
    { num: 766, english: "breathe", meaning: "호흡하다" },
    { num: 767, english: "whistle", meaning: "휘파람을 불다" },
    { num: 768, english: "draw", meaning: "끌다, 그리다" },
    { num: 769, english: "sound", meaning: "소리가 나다" },
    { num: 770, english: "save", meaning: "구하다, 저축하다" },
    { num: 771, english: "continue", meaning: "계속하다" },
    { num: 772, english: "check", meaning: "저지, 대조" },
    { num: 773, english: "sail", meaning: "항해하다, 돛" },
    { num: 774, english: "wake", meaning: "깨다, 깨우다" },
    { num: 775, english: "agree", meaning: "동의하다" },
    { num: 776, english: "hang", meaning: "걸다, 매달다" },
    { num: 777, english: "record", meaning: "기록하다" },
    { num: 778, english: "drop", meaning: "떨어지다, 방울" },
    { num: 779, english: "climb", meaning: "오르다, 기어 오르다" },
    { num: 780, english: "add", meaning: "더하다" },
    { num: 781, english: "shine", meaning: "빛나다" },
    { num: 782, english: "invite", meaning: "초대하다" },
    { num: 783, english: "join", meaning: "결합, 참가" },
    { num: 784, english: "hide", meaning: "숨기다, 숨다" },
    { num: 785, english: "bring", meaning: "가져오다" },
    { num: 786, english: "wink", meaning: "눈짓하다" },
    { num: 787, english: "shoot", meaning: "쏘다" },
    { num: 788, english: "roll", meaning: "구르다" },
    { num: 789, english: "pull", meaning: "끌다, 당기다" },
    { num: 790, english: "push", meaning: "밀다" },
    { num: 791, english: "guess", meaning: "추측하다" },
    { num: 792, english: "belong", meaning: "에 속하다" },
    { num: 793, english: "happen", meaning: "일어나다" },
    { num: 794, english: "pick", meaning: "찌르다, 고르다" },
    { num: 795, english: "shake", meaning: "흔들다, 떨다" },
    { num: 796, english: "fill", meaning: "채우다, 차다" },
    { num: 797, english: "fail", meaning: "실패하다" },
    { num: 798, english: "fight", meaning: "싸우다" },
    { num: 799, english: "fear", meaning: "두려워하다" },
    { num: 800, english: "carry", meaning: "나르다, 운반하다" },
    { num: 801, english: "dive", meaning: "뛰어들다" },
    { num: 802, english: "win", meaning: "이기다, 얻다" },
    { num: 803, english: "ride", meaning: "타다" },
    { num: 804, english: "turn", meaning: "돌다, 변화하다" },
    { num: 805, english: "need", meaning: "필요로 하다" },
    { num: 806, english: "build", meaning: "짓다, 건축하다" },
    { num: 807, english: "hurry", meaning: "서두르다" },
    { num: 808, english: "return", meaning: "돌아가다" },
    { num: 809, english: "believe", meaning: "믿다" },
    { num: 810, english: "surprise", meaning: "놀라다" },
    { num: 811, english: "gather", meaning: "모으다" },
    { num: 812, english: "throw", meaning: "던지다" },
    { num: 813, english: "raise", meaning: "올리다" },
    { num: 814, english: "count", meaning: "세다, 계산하다" },
    { num: 815, english: "smell", meaning: "냄새 맡다" },
    { num: 816, english: "spend", meaning: "소비하다, 지내다" },
    { num: 817, english: "pitch", meaning: "던지다" },
    { num: 818, english: "pop", meaning: "펑, 탁 튀다" },
    { num: 819, english: "blow", meaning: "불다" },
    { num: 820, english: "miss", meaning: "놓치다, 그리워하다" },
    { num: 821, english: "excuse", meaning: "용서, 변명" },
    { num: 822, english: "hit", meaning: "치다" },
    { num: 823, english: "tie", meaning: "매다, 묶다" },
    { num: 824, english: "touch", meaning: "닿다, 감동시키다" },
    { num: 825, english: "stay", meaning: "머무르다" },
    { num: 826, english: "enjoy", meaning: "즐기다" },
    { num: 827, english: "lose", meaning: "잃다, 지다" },
    { num: 828, english: "close", meaning: "닫다, 감다, 가까운" },
    { num: 829, english: "arrive", meaning: "도착하다" },
    { num: 830, english: "travel", meaning: "여행하다" },
    { num: 831, english: "reach", meaning: "도착하다, 닿다" },
    { num: 832, english: "hold", meaning: "쥐다, 개최하다" },
    { num: 833, english: "worry", meaning: "걱정하다" },
    { num: 834, english: "marry", meaning: "결혼하다" },
    { num: 835, english: "expect", meaning: "기대하다" },
    { num: 836, english: "understand", meaning: "이해하다" },
    { num: 837, english: "become", meaning: "되다" },
    { num: 838, english: "break", meaning: "부수다" },
    { num: 839, english: "smoke", meaning: "담배 피우다" },
    { num: 840, english: "lend", meaning: "빌려 주다" },
    { num: 841, english: "shut", meaning: "닫다" },
    { num: 842, english: "sleep", meaning: "자다" },
    { num: 843, english: "lay", meaning: "놓다, 눕히다" },
    { num: 844, english: "paint", meaning: "그리다" },
    { num: 845, english: "lead", meaning: "인도하다, 지내다" },
    { num: 846, english: "pass", meaning: "지나가다" },
    { num: 847, english: "hand", meaning: "건네주다" },
    { num: 848, english: "ancient", meaning: "고대의" },
    { num: 849, english: "nuclear", meaning: "핵의" },
    { num: 850, english: "necessary", meaning: "필요한" },
    { num: 901, english: "important", meaning: "중요한" },
    { num: 902, english: "stormy", meaning: "폭풍의" },
    { num: 903, english: "TRUE", meaning: "진실한" },
    { num: 904, english: "sad", meaning: "슬픈" },
    { num: 905, english: "gay", meaning: "명랑한, 화려한" },
    { num: 906, english: "merry", meaning: "즐거운" },
    { num: 907, english: "colorful", meaning: "화려한, 다채로운" },
    { num: 908, english: "wonderful", meaning: "놀랄 만한" },
    { num: 909, english: "peaceful", meaning: "평화로운" },
    { num: 910, english: "angry", meaning: "화난" },
    { num: 911, english: "dry", meaning: "마른" },
    { num: 912, english: "wrong", meaning: "나쁜, 틀린" },
    { num: 913, english: "heavy", meaning: "무거운" },
    { num: 914, english: "quiet", meaning: "조용한" },
    { num: 915, english: "several", meaning: "여럿의, 몇몇의" },
    { num: 916, english: "alone", meaning: "홀로, 다만 뿐" },
    { num: 917, english: "crowded", meaning: "붐비는, 혼잡한" },
    { num: 918, english: "excited", meaning: "흥분한" },
    { num: 919, english: "alive", meaning: "살아 있는" },
    { num: 920, english: "brown", meaning: "갈색의" },
    { num: 921, english: "different", meaning: "다른" },
    { num: 922, english: "difficult", meaning: "어려운" },
    { num: 923, english: "interesting", meaning: "흥미 있는" },
    { num: 924, english: "unlike", meaning: "같지 않은" },
    { num: 925, english: "least", meaning: "가장 적은" },
    { num: 926, english: "afraid", meaning: "무서워하여" },
    { num: 927, english: "cool", meaning: "시원한" },
    { num: 928, english: "pretty", meaning: "예쁜, 꽤" },
    { num: 929, english: "kind", meaning: "친절한, 종류" },
    { num: 930, english: "sick", meaning: "병든, 싫증난" },
    { num: 931, english: "useless", meaning: "쓸모 없는" },
    { num: 932, english: "busy", meaning: "바쁜" },
    { num: 933, english: "early", meaning: "이른, 일찍이" },
    { num: 934, english: "past", meaning: "과거의, 을 지나" },
    { num: 935, english: "dark", meaning: "어두운" },
    { num: 936, english: "cloudy", meaning: "흐린" },
    { num: 937, english: "short", meaning: "짧은, 작은" },
    { num: 938, english: "low", meaning: "낮은, 낮게" },
    { num: 939, english: "sincerely", meaning: "진심으로" },
    { num: 940, english: "fortunately", meaning: "다행히" },
    { num: 941, english: "finally", meaning: "마침내" },
    { num: 942, english: "immediately", meaning: "곧, 즉시" },
    { num: 943, english: "especially", meaning: "특별히" },
    { num: 944, english: "else", meaning: "그 밖에" },
    { num: 945, english: "actually", meaning: "실제로, 정말로" },
    { num: 946, english: "hardly", meaning: "거의 ~ 아니다" },
    { num: 947, english: "otherwise", meaning: "그렇지 않으면" },
    { num: 948, english: "tightly", meaning: "단단히" },
    { num: 949, english: "recently", meaning: "최근에" },
    { num: 950, english: "rapidly", meaning: "빨리, 신속히" },
    { num: 951, english: "however", meaning: "아무리~해도, 그러나" },
    { num: 952, english: "politely", meaning: "공손히" },
    { num: 953, english: "rudely", meaning: "무례하게" },
    { num: 954, english: "further", meaning: "더 멀리, 게다가" },
    { num: 955, english: "frankly", meaning: "솔직히" },
    { num: 956, english: "properly", meaning: "적당히, 올바르게" },
    { num: 957, english: "hastily", meaning: "급히, 서둘러서" },
    { num: 958, english: "rather", meaning: "오히려, 약간" },
    { num: 959, english: "together", meaning: "함께" },
    { num: 960, english: "altogether", meaning: "전혀, 대체로" },
    { num: 961, english: "suddenly", meaning: "갑자기" },
    { num: 962, english: "mostly", meaning: "대게, 대부분" },
    { num: 963, english: "correctly", meaning: "정확히" },
    { num: 964, english: "ahead", meaning: "앞에, 앞으로" },
    { num: 965, english: "instead", meaning: "대신에" },
    { num: 966, english: "quite", meaning: "매우, 아주" },
    { num: 967, english: "nearly", meaning: "거의" },
    { num: 968, english: "badly", meaning: "나쁘게, 매우" },
    { num: 969, english: "almost", meaning: "거의" },
    { num: 970, english: "exactly", meaning: "정확히, 꼭" },
    { num: 971, english: "apart", meaning: "떨어져서" },
    { num: 972, english: "afterward", meaning: "후에, 나중에" },
    { num: 973, english: "later", meaning: "후에, 나중에" },
    { num: 974, english: "maybe", meaning: "아마" },
    { num: 975, english: "perhaps", meaning: "아마" },
    { num: 976, english: "probably", meaning: "아마" },
    { num: 977, english: "either", meaning: "어느 한쪽의" },
    { num: 978, english: "neither", meaning: "도 아니다" },
    { num: 979, english: "besides", meaning: "그 밖에" },
    { num: 980, english: "anyway", meaning: "어쨌든, 아무튼" },
    { num: 981, english: "sometime", meaning: "언젠가" },
    { num: 982, english: "forward", meaning: "앞으로" },
    { num: 983, english: "since", meaning: "이래로, 때문에" },
    { num: 984, english: "once", meaning: "한 번" },
    { num: 985, english: "twice", meaning: "두 번" },
    { num: 986, english: "indeed", meaning: "참으로" },
    { num: 987, english: "seldom", meaning: "좀처럼 ~않다" },
    { num: 988, english: "upside-down", meaning: "거꾸로" },
    { num: 989, english: "whether", meaning: "인지 어떤지" },
    { num: 990, english: "unless", meaning: "하지 않으면" },
    { num: 991, english: "though", meaning: "비록 이지만" },
    { num: 992, english: "while", meaning: "하는 동안, 반면" },
    { num: 993, english: "usually", meaning: "보통, 대게" },
    { num: 994, english: "safely", meaning: "안전하게" },
    { num: 995, english: "along", meaning: "을 따라서" },
    { num: 996, english: "without", meaning: "없이" },
    { num: 997, english: "behind", meaning: "의 뒤에" },
    { num: 998, english: "beyond", meaning: "의 저쪽에" },
    { num: 999, english: "below", meaning: "의 아래에" },
    { num: 1000, english: "toward", meaning: "쪽으로" }
];
